// POST /api/tickets/:id/plan/generate — generate PRD from analyze transcript

import { db } from "@/lib/db";
import { tickets, chatMessages } from "@/lib/db/schema";
import { eq, and } from "drizzle-orm";
import { complete } from "@/lib/anthropic";

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const ticketId = parseInt(id, 10);
  const body = await request.json().catch(() => ({}));
  const { currentPrd, feedback } = body as { currentPrd?: string; feedback?: string };

  const [ticket] = await db.select().from(tickets).where(eq(tickets.id, ticketId));
  if (!ticket) return Response.json({ error: "Ticket not found" }, { status: 404 });

  // Load analyze transcript
  const analyzeMessages = await db
    .select()
    .from(chatMessages)
    .where(and(eq(chatMessages.ticketId, ticketId), eq(chatMessages.phase, "analyze")));

  const transcript = analyzeMessages
    .map((m) => `${m.role === "user" ? "User" : "AI"}: ${m.content}`)
    .join("\n\n");

  const stubPrd = `# PRD: ${ticket.title}

## Problem Statement

${ticket.description || "Based on the analysis phase discussion, this ticket addresses a key business requirement that needs implementation across the affected services."}

## Solution Overview

Implement the required changes following the existing architectural patterns. The solution will touch the identified repositories and services while maintaining backward compatibility.

## Architecture Decisions

- Follow existing service boundaries and communication patterns
- Use feature flags for gradual rollout
- Maintain backward compatibility with existing API consumers

## API Changes

- Endpoints will be added/modified as identified during the analysis phase
- All changes will be versioned and backward compatible
- Error responses will follow existing conventions

## Data Model Changes

- Schema changes (if any) will use migrations
- Indexes will be added for query performance where needed

## Key Risks

1. **Integration complexity** — Multiple services may need coordinated changes
2. **Data migration** — Existing data may need backfill
3. **Performance** — New queries should be benchmarked

## Acceptance Criteria

- All identified requirements from analysis phase are addressed
- Unit and integration tests cover the new functionality
- API documentation updated
- No regression in existing functionality

## Test Plan

- Unit tests for all new business logic
- Integration tests for API endpoints
- End-to-end tests for critical paths

*Generated by DevCycle — ${new Date().toISOString()}*`;

  const userContent = currentPrd && feedback
    ? `Revise this PRD based on the user's feedback.

Current PRD:
${currentPrd}

User feedback:
${feedback}

Ticket: "${ticket.jiraKey}: ${ticket.title}"
${ticket.description ? `Description: ${ticket.description}` : ""}

Return the complete revised PRD in markdown, keeping the same section structure. Apply the feedback precisely.`
    : `Generate a PRD for ticket "${ticket.jiraKey}: ${ticket.title}".

Analyze transcript:
${transcript || "(no transcript available)"}

Ticket description:
${ticket.description || "(no description)"}

Write a detailed PRD in markdown with sections: Problem Statement, Solution Overview, Architecture Decisions, API Changes, Data Model Changes, Key Risks, Acceptance Criteria, Test Plan.`;

  const prd = await complete(
    [{ role: "user", content: userContent }],
    {
      system: "You are a senior technical architect. Generate concise, actionable PRDs in markdown format.",
      maxTokens: 2048,
      stubResponse: stubPrd,
    }
  );

  // Save PRD path
  await db
    .update(tickets)
    .set({ prdPath: `wiki/tickets/${ticketId}/prd.md`, updatedAt: Date.now() })
    .where(eq(tickets.id, ticketId));

  return Response.json({ prd });
}
