"use client";

import { useState, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Layers, Loader2, Circle, ArrowRight, RefreshCw } from "lucide-react";
import { type Ticket } from "@/lib/fake-data";

interface TaskRow {
  id: number;
  title: string;
  description: string;
  status: string;
  waveId: number;
}

interface WaveRow {
  id: number;
  name: string;
  orderIndex: number;
  tasks: TaskRow[];
}

interface DesignPhaseProps {
  ticket: Ticket;
  onComplete: () => void;
}

export function DesignPhase({ ticket, onComplete }: DesignPhaseProps) {
  const [waves, setWaves] = useState<WaveRow[]>([]);
  const [generating, setGenerating] = useState(false);
  const [loading, setLoading] = useState(true);
  const autoGeneratedRef = useRef(false);

  const generate = async () => {
    setGenerating(true);
    try {
      const res = await fetch(`/api/tickets/${ticket.id}/design/generate`, {
        method: "POST",
      });
      const data = await res.json();
      setWaves(data.waves ?? []);
    } finally {
      setGenerating(false);
    }
  };

  useEffect(() => {
    fetch(`/api/tickets/${ticket.id}/tasks`)
      .then((r) => r.json())
      .then((data) => {
        const loaded = data.waves ?? [];
        setWaves(loaded);
        // Auto-generate if no tasks exist yet
        if (loaded.length === 0 && !autoGeneratedRef.current) {
          autoGeneratedRef.current = true;
          generate();
        }
      })
      .finally(() => setLoading(false));
  }, [ticket.id]);

  if (loading || (generating && waves.length === 0)) {
    return (
      <div className="h-full flex flex-col items-center justify-center">
        <Loader2 className="w-6 h-6 animate-spin text-amber mb-3" />
        <p className="text-sm text-muted-foreground">
          {generating ? "Generating task breakdown..." : "Loading..."}
        </p>
      </div>
    );
  }

  if (waves.length === 0) {
    return (
      <div className="h-full flex flex-col items-center justify-center">
        <Loader2 className="w-6 h-6 animate-spin text-amber mb-3" />
        <p className="text-sm text-muted-foreground">Preparing tasks...</p>
      </div>
    );
  }

  const totalTasks = waves.reduce((n, w) => n + w.tasks.length, 0);

  return (
    <div className="h-full flex flex-col">
      <div className="shrink-0 px-4 py-3 border-b border-border bg-amber/5 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Layers className="w-3.5 h-3.5 text-amber" />
          <span className="text-sm font-medium">
            {waves.length} waves &middot; {totalTasks} tasks
          </span>
        </div>
        <Button
          variant="ghost"
          size="sm"
          className="h-7 text-xs gap-1"
          onClick={generate}
          disabled={generating}
        >
          <RefreshCw className={`w-3 h-3 ${generating ? "animate-spin" : ""}`} />
          Regenerate
        </Button>
      </div>

      <ScrollArea className="flex-1 px-4">
        <div className="py-4 space-y-4">
          {waves.map((wave) => (
            <div
              key={wave.id}
              className="border border-border rounded-lg overflow-hidden"
            >
              <div className="px-3 py-2 bg-secondary/50 border-b border-border">
                <span className="text-sm font-medium">{wave.name}</span>
              </div>
              <div className="divide-y divide-border/50">
                {wave.tasks.map((task) => (
                  <div key={task.id} className="px-3 py-2.5 flex items-start gap-2">
                    <Circle className="w-3.5 h-3.5 text-muted-foreground/40 shrink-0 mt-0.5" />
                    <div className="min-w-0">
                      <p className="text-sm font-medium">{task.title}</p>
                      <p className="text-xs text-muted-foreground mt-0.5 line-clamp-2">
                        {task.description}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </ScrollArea>

      <div className="shrink-0 border-t border-border px-4 py-3 flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          Review the breakdown, then advance to Implement.
        </p>
        <Button
          size="sm"
          className="h-8 text-sm bg-amber text-background hover:bg-amber/90 gap-1"
          onClick={onComplete}
        >
          <ArrowRight className="w-3.5 h-3.5" />
          Start Implementation
        </Button>
      </div>
    </div>
  );
}
